name: Release

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.21'

    - name: File contents
      run: ls -R

    - name: Build
      run: |
        cd cmd/ma-shell
        GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o mashell
    
    - name: Archive
      run: |
          tar -czvf mashell-${{ github.event.release.tag_name }}.tar.gz -C ./cmd/ma-shell mashell
  
    - name: Upload
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: mashell-${{ github.event.release.tag_name }}.tar.gz
        asset_name: mashell-${{ github.event.release.tag_name }}.tar.gz
        asset_content_type: application/gzip